{{- if .Values.monitoring.enabled }}
{{- if (dig "serviceMonitor" "router" "enabled" true .Values.monitoring) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gas-killer.fullname" . }}-router
  labels:
    {{- include "gas-killer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gas-killer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: router
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ dig "serviceMonitor" "router" "interval" "15s" .Values.monitoring }}
{{- end }}
---
{{- if (dig "serviceMonitor" "node" "enabled" true .Values.monitoring) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gas-killer.fullname" . }}-nodes
  labels:
    {{- include "gas-killer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gas-killer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: node
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ dig "serviceMonitor" "node" "interval" "15s" .Values.monitoring }}
{{- end }}
---
{{- if (dig "serviceMonitor" "signer" "enabled" true .Values.monitoring) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gas-killer.fullname" . }}-signer
  labels:
    {{- include "gas-killer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gas-killer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: signer
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ dig "serviceMonitor" "signer" "interval" "15s" .Values.monitoring }}
{{- end }}
{{- end }}
