{{- if .Values.monitoring.enabled }}
{{- if .Values.monitoring.serviceMonitor.router.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gas-killer.fullname" . }}-router
  labels:
    {{- include "gas-killer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gas-killer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: router
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.router.interval }}
{{- end }}
---
{{- if .Values.monitoring.serviceMonitor.node.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gas-killer.fullname" . }}-nodes
  labels:
    {{- include "gas-killer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gas-killer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: node
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.node.interval }}
{{- end }}
---
{{- if .Values.monitoring.serviceMonitor.signer.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gas-killer.fullname" . }}-signer
  labels:
    {{- include "gas-killer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gas-killer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: signer
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.signer.interval }}
{{- end }}
{{- end }}
