apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "gas-killer.serviceaccount.fullname" .) .Values.secretManager.serviceAccountName }}
  labels:
    {{- include "gas-killer.labels" . | nindent 4 }}
  {{- if .Values.secretManager.gcpServiceAccount }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.secretManager.gcpServiceAccount | quote }}
  {{- end }}
