#!/usr/bin/env python3
"""Generate an N-operator overlay for the compose e2e harness.

The base docker-compose.yml defines operators node-1..node-3 (the historical
fixed fleet). This writes:

  docker-compose.fleet.yml   node-4..node-N services cloned from the node-1
                             shape (ports/keys/operator ids follow the same
                             arithmetic), router depends_on + GK_SHARD_OPERATORS
                             raised to N, and the eigenlayer setup mounting the
                             generated registration config.
  config/config.fleet.json   quorum params + testacc1..testaccN socket map
                             (maxOperatorCount = max(N, 4)).

Usage:  python3 scripts/gen_operator_fleet.py 10
Then:   export COMPOSE_FILE=docker-compose.yml:docker-compose.fleet.yml
        export TEST_ACCOUNTS=10 GK_SHARD_OPERATORS=10 GK_E2E_NODES=10
        bash scripts/run_sharded_llm_e2e_test.sh

The e2e scripts read GK_E2E_NODES (default 3) for the registration wait and
log dumps, so the harness itself stays count-agnostic.
"""

import json
import sys

N = int(sys.argv[1]) if len(sys.argv) > 1 else 10
assert N >= 3, "the base compose already defines 3 nodes; N must be >= 3"

NODE_TMPL = """  node-{i}:
    build:
      context: .
      dockerfile: node/Dockerfile
    # NO platform pin: build host-native. On Apple-silicon hosts, linux/amd64
    # under Rosetta 2 MISCOMPUTES ChaCha20-Poly1305 AEAD for inputs >=512B in
    # aws-lc-rs (handshakes and pings pass; every data broadcast fails with
    # DecryptionFailed) — the same reason docker-compose.override.yml re-pins
    # router+node-1..3 to arm64. Explicit COMPOSE_FILE lists disable that
    # automatic override, so always include it:
    #   COMPOSE_FILE=docker-compose.yml:docker-compose.override.yml:docker-compose.fleet.yml
    depends_on:
      eigenlayer:
        condition: service_completed_successfully
      ethereum:
        condition: service_started
    env_file:
      - .env
    environment:
      - HTTP_RPC=http://ethereum:8545
      - WS_RPC=ws://ethereum:8545
      - AVS_DEPLOYMENT_PATH=/app/.nodes/avs_deploy.json
      - GK_SIM_PROFILE=${{GK_SIM_PROFILE:-chain}}
      - GK_SHARD_URL=${{GK_SHARD_URL:-}}
      - GK_SHARD_OPERATOR_ID={op_id}
      - GK_SHARD_CONSUMER=${{GK_SHARD_CONSUMER:-}}
      - GK_SHARD_POLL_MS=${{GK_SHARD_POLL_MS:-300}}
    volumes:
      - ./config/.nodes/operator_keys/testacc{i}.private.bls.key.json:/app/key.json:ro
      - ./config/.nodes:/app/.nodes:ro
      - ./config/public_orchestrator.dev.json:/app/public_orchestrator.json:ro
    command:
      [
        "--key-file",
        "/app/key.json",
        "--port",
        "{p2p_port}",
        "--orchestrator",
        "/app/public_orchestrator.json",
      ]
    ports:
      - "{host_p2p}:{p2p_port}"
      - "{host_health}:8081"
    restart: unless-stopped
"""

services = []
for i in range(4, N + 1):
    services.append(
        NODE_TMPL.format(
            i=i,
            op_id=i - 1,
            p2p_port=3000 + i,
            host_p2p=4000 + i,
            host_health=9000 + i,
        )
    )

router_deps = "\n".join(
    f"      node-{i}:\n        condition: service_started" for i in range(4, N + 1)
)

fleet = f"""# GENERATED by scripts/gen_operator_fleet.py {N} — do not edit by hand.
services:
  eigenlayer:
    environment:
      - RPC_URL=http://ethereum:8545
      # environment wins over env_file (.env carries the historical
      # TEST_ACCOUNTS=3); the fleet size must drive registration.
      - TEST_ACCOUNTS={N}
    volumes:
      - ./config/.nodes:/root/.nodes
      - ./config/config.fleet.json:/bls-middleware/contracts/docker/eigenlayer/config.json

{''.join(services)}
  router:
    depends_on:
{router_deps}
    environment:
      - HTTP_RPC=http://ethereum:8545
      - WS_RPC=ws://ethereum:8545
      - AVS_DEPLOYMENT_PATH=/app/.nodes/avs_deploy.json
      - GK_SIM_PROFILE=${{GK_SIM_PROFILE:-chain}}
      - GK_SHARD_K=${{GK_SHARD_K:-2}}
      - GK_SHARD_OPERATORS=${{GK_SHARD_OPERATORS:-{N}}}
      - DATA_DIR=/app/data
      - ADMIN_KEY=${{ADMIN_KEY:-ci-admin-key}}
"""

with open("docker-compose.fleet.yml", "w") as f:
    f.write(fleet)

config = {
    "quorum": {
        "minimumStake": "1",
        "maxOperatorCount": max(N, 4),
        "kickBIPsOfOperatorStake": 10000,
        "kickBIPsOfTotalStake": 100,
    },
    "metadata": {"uri": "metadataURI"},
    "operators": {
        f"testacc{i}": {"socketAddress": f"node-{i}:{3000 + i}"} for i in range(1, N + 1)
    },
}
with open("config/config.fleet.json", "w") as f:
    json.dump(config, f, indent=4)

print(f"wrote docker-compose.fleet.yml + config/config.fleet.json for {N} operators")
print(f"run with: export COMPOSE_FILE=docker-compose.yml:docker-compose.override.yml:docker-compose.fleet.yml")
print(f"          export TEST_ACCOUNTS={N} GK_SHARD_OPERATORS={N} GK_E2E_NODES={N}")
